version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 1
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: babel-preset-latest-node
    versions:
    - 5.5.0
  - dependency-name: "@blackflux/robo-config-plugin"
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
